[package]
name = "charm_exporter"
version = "0.1.0"
authors = ["Cypher121 <8020624+Cypher121@users.noreply.github.com>"]
edition = "2018"

[dependencies.process-memory]
version = "0.4.0"

[dependencies.sysinfo]
version = "0.21.2"